#!/system/bin/sh
#added init.d support
export PATH=${PATH}:/system/bin:/system/xbin
mount -o remount,rw -t auto /system
mount -o remount,rw -t auto /
chmod -R 755 /system/etc/init.d
mount -o remount,ro -t auto /system
mount -o remount,ro -t auto /
logwrapper -k busybox run-parts /system/etc/init.d/
logwrapper -k /sbin/.magisk/busybox/run-parts /system/etc/init.d/
